defmodule Zahlungs.Catalog.Product do
  use Ecto.Schema
  import Ecto.Changeset

  schema "products" do
    field :sku, :string
    field :barcode, :string
    field :name, :string
    field :description, :string
    field :image_url, :string
    field :purchase_price, :decimal, default: Decimal.new(0)
    field :margin_percent, :decimal, default: Decimal.new(0)
    field :price, :decimal, default: Decimal.new(0)
    field :stock, :integer, default: 0
    field :active, :boolean, default: true
    field :deleted_at, :naive_datetime

    belongs_to :category, Zahlungs.Catalog.Category

    timestamps()
  end

  @doc false
  def changeset(product, attrs) do
    product
    |> cast(attrs, [
      :sku,
      :barcode,
      :name,
      :description,
      :image_url,
      :purchase_price,
      :margin_percent,
      :price,
      :stock,
      :active,
      :category_id
    ])
    # SKU is auto-generated by Catalog.create_product/1, so it is not required from
    # user input (but the column is still unique + not-null).
    |> validate_required([:name, :price, :stock])
    |> validate_length(:sku, max: 80)
    |> validate_length(:barcode, max: 64)
    |> validate_length(:name, max: 160)
    |> validate_number(:purchase_price, greater_than_or_equal_to: 0)
    |> validate_number(:margin_percent, greater_than_or_equal_to: 0)
    |> validate_number(:price, greater_than_or_equal_to: 0)
    |> validate_number(:stock, greater_than_or_equal_to: 0)
    |> unsafe_validate_unique(:sku, Zahlungs.Repo)
    |> unique_constraint(:sku)
    |> assoc_constraint(:category)
  end
end
